[package]
name = "rust-mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
ctrlc = "3.4"
env_logger = "0.10"
log = "0.4"
rand = "0.8.4"
